version: '3'
services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: 1111
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1111
    ports:
      - "3001:80"  # phpMyAdmin accessible on port 3001
    depends_on:
      - db
    networks:
      - app-network

  nodejs:
    build: .
    container_name: nodejs-app
    ports:
      - "4000:3000"  # Exposing Node.js app on port 3002
    volumes:
      - .:/usr/src/app
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
